Ms 3099
trustly/trustly-client-java pull request #13
Opened 2022-11-02 13:43 UTC by trustlyandersisraelsson

2022-11-02 14:03 UTC, BergJonatan requested changes

2022-11-03 15:11 UTC, BergJonatan requested changes

2022-11-03 15:11 UTC, BergJonatan commented on src/main/java/com/trustly/api/data/request/RequestData.java
> +    }
Sender information should be inside Attributes no?

2022-11-03 15:11 UTC, BergJonatan commented on src/main/java/com/trustly/api/requestbuilders/AccountPayout.java
> +      data.setSenderInformation(senderInformation);
SenderInformation should be inside attributes

2022-11-04 12:22 UTC, BergJonatan approved these changes

2022-11-04 12:22 UTC, BergJonatan commented on src/main/java/com/trustly/api/requestbuilders/AccountPayout.java
> +    }
I think I would prefer to get the SenderInformation object here instead of the Builder.

2022-11-04 12:36 UTC, pontus-eliason approved these changes

2022-11-04 12:36 UTC, pontus-eliason commented on pom.xml
> +        </dependency>
Is this dependency needed? Isn't in transitive to slf4j-simple?

2022-11-04 13:58 UTC, merged